name: Validate Caching

on:
  pull_request:
    branches:
      - main
      - releases/**
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - releases/**
    paths-ignore:
      - '**.md'

jobs:
  # Build and unit test
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Determine npm cache directory
      id: cache
      run: |
        echo "::set-output name=dir::$(npm config get cache)"
    - name: Restore npm cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.cache.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install node dependencies     
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
    - name: Prettier Format Check
      run: npm run format-check
    - name: ESLint Check
      run: npm run lint
    - name: Build & Test
      run: npm run test
    - name: Ensure dist/ folder is up-to-date
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        npm run build
        if [ "$(git diff --ignore-space-at-eol | wc -l)" -gt "0" ]; then
          echo "Detected uncommitted changes after build.  See status below:"
          git diff
          exit 1
        fi
        
